version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    allow:
      - dependency-name: "actions/checkout"
      - dependency-name: "actions/setup-python"
      - dependency-name: "astral-sh/setup-uv"
      - dependency-name: "hacs/action"
      - dependency-name: "home-assistant/actions/hassfest"
